global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'docker-services'
    static_configs:
      - targets: ['backend:5000', admin:80', 'frontend:80']
