global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
